import logging
from typing import Optional

from app.artifacts import load_artifacts
from app.config import settings
from app.github_publisher import GitHubPublisher, GitHubPublisherError

logger = logging.getLogger(__name__)


def branch_for_task(task_id: int | str) -> str:
    if settings.GITHUB_BRANCH_MODE == "direct":
        return settings.GITHUB_BRANCH
    return f"task/{task_id}"


async def publish_task_artifacts(redis, cid: int, tid: int, db_task_id: Optional[int] = None, role: str = "Executor") -> dict:
    artifacts = await load_artifacts(redis, cid, tid)
    if not artifacts:
        raise GitHubPublisherError("No artifacts found for this task")

    files = {artifact.path: artifact.content for artifact in artifacts}
    expected = {artifact.path: artifact.base_sha for artifact in artifacts}
    task_label = db_task_id or tid
    branch = branch_for_task(task_label)
    message = f"🤖 [Agent: {role}] Task #{task_label}: Add generated artifacts"

    publisher = GitHubPublisher()
    commit_url = publisher.create_commit(files=files, message=message, branch=branch, expected_base_shas=expected)

    pr_url = None
    if getattr(settings, "GITHUB_CREATE_PR", False) and settings.GITHUB_BRANCH_MODE != "direct":
        try:
            pr_url = publisher.create_pull_request(
                branch=branch,
                title=f"🤖 Task #{task_label}: generated artifacts",
                body="Generated by AI Agents Telegram bot.",
            )
        except Exception as e:
            logger.warning(f"GitHub PR creation failed: {str(e)[:200]}")

    return {"commit_url": commit_url, "pr_url": pr_url, "branch": branch, "files": list(files.keys())}

